### ISSUE TITLE
Provide ability to treat key containing dots as string literal

### ISSUE THREAD

**Issue by philipobenito** [glopezdetorre/dot-notation-access#1]
There are situations where I might want an array key to contain dots. As things stand, a traversal of the path will always be attempted.

Would you consider the ability to treat a key as a string literal?

**Comment by gorkaio** [comment]
Sorry for the long time passed since your message! Could you please elaborate on this or, better yet, provide a failing test we can work on?

**Comment by gorkaio** [comment]
As discussed in #3, that is an intended restriction on valid keys to avoid confusion between keys and their traversal access. Thanks!
