### ISSUE TITLE
Ability to work with all valid keys

### ISSUE THREAD

**Issue by mirfilip** [glopezdetorre/dot-notation-access#3]
Hi, please have a look at [these examples](https://github.com/mirfilip/dot-notation-access/blob/feature/accessing-with-special-chars/tests/DotNotationAccessArrayTest.php#L398).

I've added the simplest of test to have a discussion ground. The issue is: the way [isValidKey](https://github.com/glopezdetorre/dot-notation-access/blob/master/src/DotNotationAccessArray.php#L145) method works, it makes the project usable only with a limited subset of real arrays.

Currently, the arrays that have any kind of special chars as a part of string key in associative array, are not supported.

**Comment by gorkaio** [comment]
Do you have any real use case scenarios where these type of keys would be needed? In my opinion, the keys should be as strictly limited as possible: using spaces,  special chars or (specially) dots as key names might be problematic and does not sound like something I would recommend.

**Comment by mirfilip** [comment]
If the library claims to be a dot notation wrapper around the array, then every legal array access should work as well.

``` php
$test = ['foo bar' => 1];
echo $test['foo bar']; // 1 // legal array access
new DotNotationAccessArray($test) // InvalidArgumentException
```

Two real life scenarios I stumbled upon this limitations are:
1. Working with framework configuration arrays where it's not uncommon to have `my.super.service.key` as a key.
2. Writing any API that has a request represented as an array and wrapping it with this library. You don't really have control upon user input and there is no reason to limit input to fit the util library.

Actually, I can come up with more sane scenarios where it matters.

Anyway, I just noticed this is not a bug but rather a design decision of yours and I have moved on. Feel free to close it if that's by design.

**Comment by gorkaio** [comment]
Hi Miroslaw,

Thanks for your comments.

Actually, the first scenario is the intended use of this library though put backwards, I think. I wrote it to be able to define configuration as an array in plain PHP and later access it in a more suitable way when defining services in a DI, for example. Thus, in the intended use you would never have keys defined with dots, as this is precisely what the library does for you from a plain PHP array.

The second scenario is an interesting use, though it would probably be safer to use json for that.

I'm closing the issue, but please feel free to fork if you need these features. As you said, they are not in the intended use of this library but of course they might be perfectly valid for your requirements :)
